#!/usr/bin/env bash

NUMBER=$1
NAME=$2

function useage {
      echo "Useage: wsname <workspace_number> <name>"
}

if [ $# -eq 0 ]
then
  useage
  exit 1
fi

if [ -z "$NAME" ]
then
  useage
  exit 1
fi

echo 'rename workspace ${NUMBER} to "${NUMBER}: ${NAME}"'
i3-msg 'rename workspace ${NUMBER} to "${NUMBER}: ${NAME}"'
